name = "konfido-lead-handler"
main = "src/index.js"
compatibility_date = "2024-01-01"

[vars]
ZEPTOMAIL_API_TOKEN = "Zoho-enczapikey PHtE6r1cQOC6jmd5+xMC5PC8FcH2Z9goqbwyeQBC44ZKW6QKGk1TqY1+wDLmqBx5UvlBEPDKzYluueiZse3QIzzrMDpJXWqyqK3sx/VYSPOZsbq6x00UsV0cdkLfU4DscdBp3CTSvNrYNA=="
TO_EMAIL = "info@konfido.co.in"
FROM_EMAIL = "enquiry@konfido.co.in"
